# Generated by Django 5.2.4 on 2026-07-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Automatically generated from the Hindi or English title.', max_length=270, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(max_length=500, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Title'),
        ),
    ]
