# Generated by Django 5.2.4 on 2026-07-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_content_alter_article_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, help_text='Optional: add a short summary or leave it blank.', max_length=500, verbose_name='Summary'),
        ),
    ]
