# Generated by Django 5.2.4 on 2026-07-22 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_article_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-created_at', '-published_at')},
        ),
    ]
