# Generated by Django 5.2.4 on 2026-07-22 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-created_at', '-pk', '-published_at')},
        ),
    ]
