# Generated by Django 5.2.4 on 2026-07-22 10:18

import chandauli_samachar.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_article_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=chandauli_samachar.fields.CompleteUnicodeSlugField(allow_unicode=True, blank=True, help_text='Automatically generated from the Hindi or English title.', max_length=270, unique=True, verbose_name='Slug'),
        ),
    ]
