# Generated by Django 5.2.4 on 2026-07-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_city', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Automatically generated from the Hindi or English name.'),
        ),
        migrations.AlterField(
            model_name='state',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Automatically generated from the Hindi or English name.', unique=True),
        ),
    ]
