# Generated by Django 5.2.4 on 2026-07-22 10:18

import chandauli_samachar.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state_city', '0002_alter_city_slug_alter_state_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=chandauli_samachar.fields.CompleteUnicodeSlugField(allow_unicode=True, blank=True, help_text='Automatically generated from the Hindi or English name.'),
        ),
        migrations.AlterField(
            model_name='state',
            name='slug',
            field=chandauli_samachar.fields.CompleteUnicodeSlugField(allow_unicode=True, blank=True, help_text='Automatically generated from the Hindi or English name.', unique=True),
        ),
    ]
