# Generated by Django 5.2.4 on 2026-07-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='नाम')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ईमेल')),
                ('phone', models.CharField(max_length=20, verbose_name='मोबाइल')),
                ('subject', models.CharField(max_length=180, verbose_name='विषय')),
                ('message', models.TextField(verbose_name='संदेश')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='निस्तारित')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
