# Generated by Django 5.2.4 on 2026-07-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Automatically generated from the Hindi or English name.', unique=True, verbose_name='Slug'),
        ),
    ]
