# Generated by Django 5.2.4 on 2026-07-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Internal name')),
                ('advertiser', models.CharField(blank=True, max_length=120, verbose_name='Advertiser label')),
                ('headline', models.CharField(blank=True, max_length=180)),
                ('subheadline', models.CharField(blank=True, max_length=220)),
                ('contact', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='advertisements/%Y/%m/')),
                ('destination_url', models.URLField(blank=True)),
                ('cta_text', models.CharField(blank=True, default='Call Now', max_length=40)),
                ('placement', models.CharField(choices=[('home_sidebar', 'Homepage sidebar'), ('home_wide', 'Homepage wide'), ('article_sidebar', 'Article sidebar'), ('article_inline', 'Article inline')], default='home_sidebar', max_length=30)),
                ('style', models.CharField(choices=[('creative', 'Text creative'), ('image', 'Image banner')], default='creative', max_length=12)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-priority', '-created_at'),
            },
        ),
    ]
